# Generated by Django 5.0.1 on 2024-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('ImageUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
    ]
